<<<<<<< Updated upstream
ALCHEMY_MAIN = "ft7Qh8xHZ-RoZZ_c1nIjEjGYJUNAHQYn";
ALCHEMY_SEPOLIA = "BrqaHU5n9sK_pF9ppvP0CmdgUoIiwgTG";
ALCHEMY_OPTIMISM = "64hYA9WzymOzXX8htmi1hKEF8EnfYu02";
ALCHEMY_BASE = "QbxAc8wts9HXSclpJhBGmE6WRboZ_bn1";
ALCHEMY_ARBITRUM = "40aNIk9k-y9mfiNsx5SnVT23kzkO7N1B";
=======
ALCHEMY_MAIN = "S1crhDhRl9qxjR6OeKFkmmmQyMZ3NB1l";
ALCHEMY_SEPOLIA = "XyHLiyu5-Vtia1efPxqR69eQXHvmQPZG";
ALCHEMY_OPTIMISM = "3glo3PS5jzG2O739NgDE_ioXIsl_j5mR";
ALCHEMY_BASE = "vrnasMvVzsFXtHLMYz6wTeNPf9TYueoh";
ALCHEMY_ARBITRUM = "PDuLrRd1VlYHKgB2I88kmrfhUOcaiu9e";
>>>>>>> Stashed changes
