ALCHEMY_KEY = "ft7Qh8xHZ-RoZZ_c1nIjEjGYJUNAHQYn";
// ALCHEMY_SEPOLIA = "ft7Qh8xHZ-RoZZ_c1nIjEjGYJUNAHQYn";
// ALCHEMY_OPTIMISM = "ft7Qh8xHZ-RoZZ_c1nIjEjGYJUNAHQYn";
// ALCHEMY_BASE = "ft7Qh8xHZ-RoZZ_c1nIjEjGYJUNAHQYn";
// ALCHEMY_ARBITRUM = "ft7Qh8xHZ-RoZZ_c1nIjEjGYJUNAHQYn";
// ALCHEMY_POLYGON = "ft7Qh8xHZ-RoZZ_c1nIjEjGYJUNAHQYn";
// ALCHEMY_ZORA = "ft7Qh8xHZ-RoZZ_c1nIjEjGYJUNAHQYn";
